#! /usr/bin/bash

# activate virtual environment
if [ -d ".sangeet_app_venv" ]; then
	source .sangeet_app_venv/bin/activate
	echo "Virtual environment enabled"
else
	echo "No virtual environment setup. Please run setup first"
	exit
fi
pip freeze > requirements.txt

# set environment variables
export FLASK_APP=sangeet

if [ "$1" == 'r' ]; then
	echo "Starting the application Sangeet"
	flask run --debug
fi
